site_name: "LXDドキュメント翻訳プロジェクト"
theme: readthedocs
docs_dir: 'doc'
pages:
  - Home: index.md
  - API拡張: api-extensions.md
  - アーキテクチャ: architectures.md
  - バックアップ: backup.md
  - cloud-initファイル: cloud-init.md
  - クラスタリング: clustering.md
  - 設定: configuration.md
  - コンテナ: containers.md
  - コンテナ実行環境: container-environment.md
  - コントリビュート: contributing.md
  - デーモンの動作: daemon-behavior.md
  - データベース: database.md
  - デバッグ: debugging.md
  - コンテナ〜ホスト間の通信: dev-lxd.md
  - 環境変数: environment.md
  - FAQ: faq.md
  - イメージの扱い: image-handling.md
  - ライブマイグレーション: migration.md
  - ネットワーク: networks.md
  - preseeded YAML: preseed.md
  - プロダクション環境のセットアップ: production-setup.md
  - プロファイル: profiles.md
  - プロジェクト: projects.md
  - 動作環境: requirements.md
  - REST API: rest-api.md
  - セキュリティ: security.md
  - サーバ: server.md
  - ストレージ: storage.md
  - システムコールのインターセプト: syscall-interception.md
  - ユーザー名前空間のIDマッピング: userns-idmap.md
