site_name: "LXDドキュメント翻訳プロジェクト"
theme: readthedocs
docs_dir: 'doc'
nav:
- はじめに:
    - はじめに: index.md
    - 動作環境: requirements.md
    - FAQ: faq.md
    - セキュリティ: security.md
    - コントリビュート: contributing.md
- 設定:
    - 設定: configuration.md
    - コンテナ: containers.md
    - インスタンス: instances.md
    - ネットワーク: networks.md
    - ネットワーク ACL: network-acls.md
    - ネットワークフォワード: network-forwards.md
    - preseeded YAML: preseed.md
    - プロファイル: profiles.md
    - プロジェクト: projects.md
    - サーバ: server.md
    - ストレージプール: storage.md
    - 仮想マシン: virtual-machines.md
- イメージ:
    - アーキテクチャ: architectures.md
    - cloud-initファイル: cloud-init.md
    - イメージの扱い: image-handling.md
- オペレーション:
    - バックアップ: backup.md
    - クラスタリング: clustering.md
    - プロダクション環境のセットアップ: production-setup.md
    - Remotes: remotes.md
- REST API:
    - REST API: rest-api.md
    - API拡張: api-extensions.md
    - コンテナ API: dev-lxd.md
    - イベント API: events.md
- 内部動作とデバッグ:
    - コンテナ実行環境: container-environment.md
    - コンテナのマイグレーション: migration.md
    - デーモンの動作: daemon-behavior.md
    - データベース: database.md
    - デバッグ: debugging.md
    - 環境変数: environment.md
    - システムコールのインターセプト: syscall-interception.md
    - ユーザー名前空間の設定: userns-idmap.md
- 外部リソース:
    - プロジェクトリポジトリー: https://github.com/lxc/lxd
    - イメージサーバー: https://images.linuxcontainers.org/
